### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jim-rosales** [claytondecker/colmar-academy#5]
### Criteria 1: HTML Structure  
* _Score Level:_ 4
* _Comment(s):_ HTML implementation enables proper use of media queries
 
### Criteria 2: Visual Layout for Both Desktop and Mobile Sizes
* _Score Level:_ 4
* _Comment(s):_ Desktop AND mobile layouts match the wireframe in all sections
 
### Criteria 3: Responsive Design (Media Queries, Responsive Units, etc.)
* _Score Level:_ 4
* _Comment(s):_ Media queries kick in at appropriate breakpoints
 
### Criteria 4: Visual Design and Accessibility (Color Palette, Typography, Transitions, etc.)
* _Score Level:_ 4
* _Comment(s):_ An accessible color palette was chosen. Typographic considerations were made. CSS transitions were used
 
### Overall Score: 16/16

Congrats on finishing your capstone project! Overall you did an excellent job with the project, few are as responsive as yours since you did a diligent job of ensuring that your page adapted to any screen width appropriately. You also did an excellent job ensuring that your code was readable by making use comments throughout your project.

To expand on your project consider researching [variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables) and then analyze how you might make use of them on future projects. They are a great tool that allows you to increase the maintainability of your CSS file and it's readability.

**Comment by claytondecker** [comment]
Thanks!!
